// Opciones de "¿Quién te invitó?" en el registro. El formulario solo acepta estos valores
// (los usa invito-field.js y la validación de rsvp-form.js). "asesores" es la lista de
// ejecutivos CiiSA | PSW; se muestran nombre y primer apellido porque es una página pública
// (los correos no van aquí: viven en la carpeta privada). Para agregar o quitar un ejecutivo,
// edita esta lista; mantén la misma lista en la propiedad de HubSpot para que ambas fuentes coincidan.
window.CIISA_INVITO = {
  canales: [
    'LinkedIn',
    'Google',
    'Nadie, me enteré por mi cuenta'
  ],
  asesores: [
    'Aaron Moreno',
    'Adrián Sosa',
    'Adriel Nacianceno',
    'Aideé Silva',
    'Aily Gallardo',
    'Alan Tabares',
    'Albino Alvarado',
    'Alejandro Alonso',
    'Alejandro González',
    'Alejandro Hernández',
    'Alejandro Mendoza',
    'Alma Flores',
    'Amel Delgado',
    'Ana Colis',
    'Ana Medina',
    'Andrea Orta',
    'Andrea Vazquez',
    'Angela Osorio',
    'Angela Sánchez',
    'Antonio González',
    'Arnulfo Tamez',
    'Augusto Sanoja',
    'Aurora Gutierrez',
    'Aurora Villarreal',
    'Axel Chávez',
    'Brandon Castro',
    'Brayan Marín',
    'Brenda Arriaga',
    'Bruno Peña',
    'Carlos Moreno',
    'Carlos Salazar',
    'Carlos Velásquez',
    'Carlos Zuñiga',
    'Carolina Almanza',
    'Celeste Pérez',
    'César de la Rosa',
    'Cesar Molano',
    'Claudia Gutierrez',
    'Cynthia Garza',
    'Cynthia Pérez',
    'Daniel Carreño',
    'Daniel Flores',
    'David González',
    'David Rojas',
    'David Villarreal',
    'Deyanira Sauceda',
    'Diana Aguilar',
    'Diana Orozco',
    'Diego Aranda',
    'Diego de la Rosa',
    'Diego Mezquitic',
    'Edgar Cervantes',
    'Eduardo Pérez',
    'Eduardo Reyes',
    'Edwin Villalón',
    'Emanuel Flores',
    'Erick Moreno',
    'Erika López',
    'Esmeralda de León',
    'Esmeralda Galaviz',
    'Esmeralda Treviño',
    'Estrella del Angel',
    'Fátima Galaviz',
    'Fernando González',
    'Fernando Herrera',
    'Fernando Ortiz',
    'Gabriela Treviño',
    'Gerardo Salgado',
    'Giselle Valdes',
    'Grecia de la Merced',
    'Guillermo Medina',
    'Héctor Arriaga',
    'Ileana Ibarra',
    'Ilse Sanchez',
    'Ingrid Acuña',
    'Iris Salinas',
    'Isaac Sánchez',
    'Isbrain Vieytez',
    'Iván Garza',
    'Ivonne Rodríguez',
    'Jair Martínez',
    'Jesus Cuellar',
    'Jesús González',
    'Jesús Rosas',
    'Jesus Zuñiga',
    'Jordan García',
    'Jorge Vanegas',
    'Jose Alonso',
    'José García',
    'José Hernández',
    'José Luis Mesta',
    'José Silva',
    'Jose Villarreal',
    'Julio César Cruz',
    'Julio Liguez',
    'Junior Torres',
    'Karen Flores',
    'Karla Contreras',
    'Karla Mejia',
    'Karyme Ferrer',
    'Kevin Córdova',
    'Keyla Aleman',
    'Laura Morales',
    'Laura Rojas',
    'Leonardo Sánchez',
    'Liliana Torres',
    'Lizbeth Marrufo',
    'Lizette Morales',
    'Lorena Carrera',
    'Lorena Guevara',
    'Loreto Torres',
    'Lucas Córdova',
    'Luis Esquivel',
    'Luis Méndez',
    'Magali Cázares',
    'Magdalena Escalera',
    'Magdalena Gómez',
    'Marcelo Villarreal',
    'María Dolores Santos',
    'María Hernández',
    'Mario Cavazos',
    'Marisol Villarreal',
    'Martín Cortés',
    'Martinique Ledezma',
    'Mauricio Ponce',
    'Mauricio Ramos',
    'Mauro Guzmán',
    'Mayela Cabrera',
    'Mayela Flores',
    'Mayra Morín',
    'Michael Medina',
    'Michelle García',
    'Miguel Ayala',
    'Miguel Rodríguez',
    'Miguel Zapata',
    'Mildred Rodríguez',
    'Miriam Ramirez',
    'Misael Ortega',
    'Monica Guerra',
    'Monserrat Salazar',
    'Nadia Puente',
    'Nallely Ramos',
    'Neithan Marroquín',
    'Omar Ayala',
    'Oscar Aguirre',
    'Oscar Ortíz',
    'Oziel Martínez',
    'Paloma Escalona',
    'Paola Muñiz',
    'Paola Venegas',
    'Ricardo Rodriguez',
    'Ricardo Torres',
    'Rocío Lara',
    'Rodolfo Rivera',
    'Rosario Lara',
    'Ruben Flores',
    'Salma de la Rosa',
    'Sergio Reyes',
    'Silvestre Vargas',
    'Silvia Cavanzo',
    'Sofía Peña',
    'Sofía Pérez',
    'Tanya Serrato',
    'Vanessa Osorio',
    'Vanessa Plascencia',
    'Vanessa Serna',
    'Verónica Hernández',
    'Victor Alvarez',
    'Víctor Hernández',
    'Victor Treviño',
    'Viviana Garay',
    'Xena González',
    'Yessica Rodríguez',
    'Yuliana Guevara'
  ]
};
